jobs:
  Job1:
    name: Job 1
    steps:
      - type: maven
        maven-version: defaultProvidedVersion
        pom-location: pom.xml
        name: clean test
        goals: clean test
    parallelism: 2
    allow-reuse: false
    runs-on:
      self-hosted:
        - requirement: equals
          name: OS
          parameter: teamcity.agent.jvm.os.name
          value: Linux
    features:
      - type: free-disk-space
        required-space: '-9'
  Job1clone:
    name: Job 1 clone
    steps:
      - type: maven
        maven-version: defaultProvidedVersion
        pom-location: pom.xml
        name: clean test
        goals: clean test
    parallelism: 2
    allow-reuse: false
    runs-on:
      self-hosted:
        - requirement: equals
          name: OS
          parameter: teamcity.agent.jvm.os.name
          value: Linux
